package net.anzix.osm.upload.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table GPX.
 */
public class Gpx {

    private Long id;
    /**
     * Not-null value.
     */
    private String type;
    /**
     * Not-null value.
     */
    private String location;
    private java.util.Date uploaded;
    private java.util.Date created;

    public Gpx() {
    }

    public Gpx(Long id) {
        this.id = id;
    }

    public Gpx(Long id, String type, String location, java.util.Date uploaded, java.util.Date created) {
        this.id = id;
        this.type = type;
        this.location = location;
        this.uploaded = uploaded;
        this.created = created;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getType() {
        return type;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Not-null value.
     */
    public String getLocation() {
        return location;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setLocation(String location) {
        this.location = location;
    }

    public java.util.Date getUploaded() {
        return uploaded;
    }

    public void setUploaded(java.util.Date uploaded) {
        this.uploaded = uploaded;
    }

    public java.util.Date getCreated() {
        return created;
    }

    public void setCreated(java.util.Date created) {
        this.created = created;
    }

    public String getName() {
        return location.substring(location.lastIndexOf("/"));
    }

    public String getPath() {
        int idx = location.lastIndexOf("/");
        if (idx > 0) {
            return location.substring(0, location.lastIndexOf("/"));
        } else {
            return location;
        }
    }
}
