package net.anzix.osm.upload.data;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table SOURCE.
 */
public class Source {

    private Long id;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String location;
    private String parameters;

    public Source() {
    }

    public Source(Long id) {
        this.id = id;
    }

    public Source(Long id, String type, String location, String parameters) {
        this.id = id;
        this.type = type;
        this.location = location;
        this.parameters = parameters;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getLocation() {
        return location;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLocation(String location) {
        this.location = location;
    }

    public String getParameters() {
        return parameters;
    }

    public void setParameters(String parameters) {
        this.parameters = parameters;
    }

}
